---
namespace: rhdp
name: workshop
version: 1.0.0
readme: README.md
authors:
  - Your Name <your.email@example.com>

description: Ansible collection for deploying the OpenShift Advanced Application Platform Demo"

license:
  - GPL-2.0-or-later

tags:
  - openshift
  - workshop
  - platform_engineering
  - advanced_application_platform

dependencies: {}

build_ignore:
  - .git
  - .gitignore
  - .DS_Store
